# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [main, develop]

  push:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    services:
      rmq:
        image: rabbitmq
        ports: ["5672:5672"]

    steps:
      - name: Sleep 2s to make rmq start
        run: sleep 2

      - uses: actions/checkout@main

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Check code
        run: uv run ruff check

      - name: Test with pytest
        run: uv run pytest
